<a href="https://colab.research.google.com/github/EastHuni/Bigdata/blob/main/%EB%B9%85%EB%8D%B0%EC%9D%B4%ED%84%B0%20%EB%B6%84%EC%84%9D%EA%B8%B0%EC%82%AC%205%ED%9A%8C%20(%EC%9E%91%EC%97%85%ED%98%951).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 신용카드서비스를 떠나는 고객을 찾아라
- 나이, 급여, 결혼 상태, 신용 카드 한도, 신용 카드 카테고리 등의 컬럼이 있음
- 평가: ROC-AUC, 정확도(Accuracy), F1, 정밀도(Precision), 재현율(Recall)을 구하시오
- target : Attrition_Flag (1:이탈, 0:유지)
- csv파일 생성 : 수험번호.csv (예시 아래 참조)
~~~
CLIENTNUM,Attrition_Flag
788544108,0.633
719356008,0.123
712142733,0.355
~~~


### 평가(분류)
~~~
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score

# 정확도
print(accuracy_score(y_test, pred))

# 정밀도
print(precision_score(y_test, pred))

# 재현율 (민감도)
print(recall_score(y_test, pred))

# F1
print(f1_score(y_test , pred))

# roc-auc
print(roc_auc_score(y_test, pred_proba))
~~~

## 데이터 불러오기

In [ ]:
import pandas as pd

train = pd.read_csv()
test =  pd.read_csv()
# train = pd.read_csv("train.csv")
# test =  pd.read_csv("test.csv")

In [ ]:
print(train.shape, test.shape)

(8101, 21) (2026, 20)

In [ ]:
train.head()

,CLIENTNUM,Customer_Age,Gender,Dependent_count,Education_Level,Marital_Status,Income_Category,Card_Category,Months_on_book,Total_Relationship_Count,...,Contacts_Count_12_mon,Credit_Limit,Total_Revolving_Bal,Avg_Open_To_Buy,Total_Amt_Chng_Q4_Q1,Total_Trans_Amt,Total_Trans_Ct,Total_Ct_Chng_Q4_Q1,Avg_Utilization_Ratio,Attrition_Flag
0,778461408,38,M,1,High School,Married,$80K - $120K,Blue,23,4,...,2,22149.0,987,21162.0,1.633,2409,36,0.800,0.045,0
1,718263108,44,F,3,Unknown,Divorced,Less than $40K,Blue,32,3,...,2,1693.0,1457,236.0,0.919,2829,42,0.615,0.861,1
2,780384483,49,M,4,Unknown,Unknown,$80K - $120K,Blue,39,2,...,2,2886.0,925,1961.0,0.946,5481,58,0.758,0.321,1
3,719592483,43,F,5,Graduate,Single,Unknown,Blue,34,6,...,3,4607.0,2440,2167.0,0.646,4825,77,0.878,0.530,0
4,771453033,47,M,3,High School,Married,$60K - $80K,Blue,35,5,...,2,17343.0,1280,16063.0,1.314,3170,57,0.629,0.074,0

In [ ]:
train.isna().sum() # 결측치 하나도 없는거 확인완료

CLIENTNUM                   0
Customer_Age                0
Gender                      0
Dependent_count             0
Education_Level             0
Marital_Status              0
Income_Category             0
Card_Category               0
Months_on_book              0
Total_Relationship_Count    0
Months_Inactive_12_mon      0
Contacts_Count_12_mon       0
Credit_Limit                0
Total_Revolving_Bal         0
Avg_Open_To_Buy             0
Total_Amt_Chng_Q4_Q1        0
Total_Trans_Amt             0
Total_Trans_Ct              0
Total_Ct_Chng_Q4_Q1         0
Avg_Utilization_Ratio       0
Attrition_Flag              0
dtype: int64

In [ ]:
train.describe(include ='O')

       Gender Education_Level Marital_Status Income_Category Card_Category
count    8101            8101           8101            8101          8101
unique      2               7              4               6             4
top         F        Graduate        Married  Less than $40K          Blue
freq     4304            2481           3775            2860          7543

In [ ]:
train['Attrition_Flag'].value_counts()

Attrition_Flag
0    6815
1    1286
Name: count, dtype: int64

In [ ]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8101 entries, 0 to 8100
Data columns (total 21 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   CLIENTNUM                 8101 non-null   int64
 1   Customer_Age              8101 non-null   int64
 2   Gender                    8101 non-null   object
 3   Dependent_count           8101 non-null   int64
 4   Education_Level           8101 non-null   object
 5   Marital_Status            8101 non-null   object
 6   Income_Category           8101 non-null   object
 7   Card_Category             8101 non-null   object
 8   Months_on_book            8101 non-null   int64
 9   Total_Relationship_Count  8101 non-null   int64
 10  Months_Inactive_12_mon    8101 non-null   int64
 11  Contacts_Count_12_mon     8101 non-null   int64
 12  Credit_Limit              8101 non-null   float64
 13  Total_Revolving_Bal       8101 non-null   int64
 14  Avg_Open_To_Buy           8101 non-null   float64
 15  Total_Amt_Chng_Q4_Q1      8101 non-null   float64
 16  Total_Trans_Amt           8101 non-null   int64
 17  Total_Trans_Ct            8101 non-null   int64
 18  Total_Ct_Chng_Q4_Q1       8101 non-null   float64
 19  Avg_Utilization_Ratio     8101 non-null   float64
 20  Attrition_Flag            8101 non-null   int64
dtypes: float64(5), int64(11), object(5)
memory usage: 1.3+ MB

## 데이터 전처리 & 피처엔지니어링

In [ ]:
#결측치 없음, 이상치 없음, 숫자로다 바꿔주면 될듯?
target = train.pop('Attrition_Flag')
target_id = test.pop('CLIENTNUM')
df = pd.concat([train, test], axis = 0)
data_oh = pd.get_dummies(df)
train_oh = data_oh[:len(train)].copy()
test_oh = data_oh[len(train):].copy()
print(train.shape, test.shape, train_oh.shape, test_oh.shape)

(8101, 20) (2026, 19) (8101, 38) (2026, 38)

In [ ]:
# from sklearn.preprocessing import LabelEncoder
# cols = {'Gender', 'Education_Level', 'Marital_Status','Income_Category', 'Card_Category'}
# le = LabelEncoder()
# for col in cols:
#   train[col] = le.fit_transform(train[col])
#   test[col] = le.transform(test[col])
train_oh.info()

<class 'pandas.core.frame.DataFrame'>
Index: 8101 entries, 0 to 8100
Data columns (total 38 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   CLIENTNUM                       8101 non-null   float64
 1   Customer_Age                    8101 non-null   int64
 2   Dependent_count                 8101 non-null   int64
 3   Months_on_book                  8101 non-null   int64
 4   Total_Relationship_Count        8101 non-null   int64
 5   Months_Inactive_12_mon          8101 non-null   int64
 6   Contacts_Count_12_mon           8101 non-null   int64
 7   Credit_Limit                    8101 non-null   float64
 8   Total_Revolving_Bal             8101 non-null   int64
 9   Avg_Open_To_Buy                 8101 non-null   float64
 10  Total_Amt_Chng_Q4_Q1            8101 non-null   float64
 11  Total_Trans_Amt                 8101 non-null   int64
 12  Total_Trans_Ct                  8101 non-null   int64
 13  Total_Ct_Chng_Q4_Q1             8101 non-null   float64
 14  Avg_Utilization_Ratio           8101 non-null   float64
 15  Gender_F                        8101 non-null   bool
 16  Gender_M                        8101 non-null   bool
 17  Education_Level_College         8101 non-null   bool
 18  Education_Level_Doctorate       8101 non-null   bool
 19  Education_Level_Graduate        8101 non-null   bool
 20  Education_Level_High School     8101 non-null   bool
 21  Education_Level_Post-Graduate   8101 non-null   bool
 22  Education_Level_Uneducated      8101 non-null   bool
 23  Education_Level_Unknown         8101 non-null   bool
 24  Marital_Status_Divorced         8101 non-null   bool
 25  Marital_Status_Married          8101 non-null   bool
 26  Marital_Status_Single           8101 non-null   bool
 27  Marital_Status_Unknown          8101 non-null   bool
 28  Income_Category_$120K +         8101 non-null   bool
 29  Income_Category_$40K - $60K     8101 non-null   bool
 30  Income_Category_$60K - $80K     8101 non-null   bool
 31  Income_Category_$80K - $120K    8101 non-null   bool
 32  Income_Category_Less than $40K  8101 non-null   bool
 33  Income_Category_Unknown         8101 non-null   bool
 34  Card_Category_Blue              8101 non-null   bool
 35  Card_Category_Gold              8101 non-null   bool
 36  Card_Category_Platinum          8101 non-null   bool
 37  Card_Category_Silver            8101 non-null   bool
dtypes: bool(23), float64(6), int64(9)
memory usage: 1.2 MB

In [ ]:
print(train.select_dtypes(include = 'int').columns)
print(train.select_dtypes(include = 'float').columns)
scol = ['Customer_Age', 'Dependent_count', 'Months_on_book',
       'Total_Relationship_Count', 'Months_Inactive_12_mon',
       'Contacts_Count_12_mon', 'Total_Revolving_Bal', 'Total_Trans_Amt',
       'Total_Trans_Ct','Credit_Limit', 'Avg_Open_To_Buy', 'Total_Amt_Chng_Q4_Q1',
       'Total_Ct_Chng_Q4_Q1', 'Avg_Utilization_Ratio']

Index(['CLIENTNUM', 'Customer_Age', 'Dependent_count', 'Months_on_book',
       'Total_Relationship_Count', 'Months_Inactive_12_mon',
       'Contacts_Count_12_mon', 'Total_Revolving_Bal', 'Total_Trans_Amt',
       'Total_Trans_Ct'],
      dtype='object')
Index(['Credit_Limit', 'Avg_Open_To_Buy', 'Total_Amt_Chng_Q4_Q1',
       'Total_Ct_Chng_Q4_Q1', 'Avg_Utilization_Ratio'],
      dtype='object')

In [ ]:
# 스케일링
# from sklearn.preprocessing import MinMaxScaler
# sc = MinMaxScaler()
# train_sc = train_oh.copy()
# test_sc = test_oh.copy()
# display(train_sc[scol].head(2))
# train_sc[scol] = sc.fit_transform(train_sc[scol])
# test_sc[scol] = sc.transform(test_sc[scol])
# display(train_sc[scol].head(2))

In [ ]:
target.value_counts()

Attrition_Flag
0    6815
1    1286
Name: count, dtype: int64

## 검증 데이터 분리

In [ ]:
train_oh.shape, target.shape, test_oh.shape

((8101, 38), (8101,), (2026, 38))

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_val, y_train, y_val = train_test_split(train_oh, target, test_size = 0.2, random_state = 0)
X_train.shape, X_val.shape, y_train.shape, y_val.shape

((6480, 38), (1621, 38), (6480,), (1621,))

## 모델 & 평가

In [ ]:
from sklearn.ensemble import RandomForestClassifier
rfcf = RandomForestClassifier()
rfcf.fit(X_train, y_train)
pred1 = rfcf.predict(X_val)
pred2 = rfcf.predict_proba(X_val)
pred1[:10]
pred2[:10]

array([[0.96, 0.04],
       [0.99, 0.01],
       [0.91, 0.09],
       [0.98, 0.02],
       [1.  , 0.  ],
       [0.27, 0.73],
       [0.92, 0.08],
       [0.81, 0.19],
       [0.98, 0.02],
       [1.  , 0.  ]])

In [ ]:
from sklearn.metrics import roc_auc_score, precision_score, recall_score, f1_score, accuracy_score
# 정확도
print(accuracy_score(y_val, pred1))

# 정밀도
print(precision_score(y_val, pred1))

# 재현율 (민감도)
print(recall_score(y_val, pred1))

# F1
print(f1_score(y_val, pred1))

# roc-auc
print(roc_auc_score(y_val, pred2[:,1]))
#베이스 라인
#0.9568167797655768
#0.927536231884058
#0.7773279352226721
#0.8458149779735683
#0.9868155861605643

0.958667489204195
0.9326923076923077
0.7854251012145749
0.8527472527472527
0.9870881436038872

In [ ]:
import lightgbm as lgb
lgbmc = lgb.LGBMClassifier(random_state = 0, verbose = -1)
lgbmc.fit(X_train, y_train)
pred1 = lgbmc.predict(X_val)
pred2 = lgbmc.predict_proba(X_val)
# 정확도
print(accuracy_score(y_val, pred1))

# 정밀도
print(precision_score(y_val, pred1))

# 재현율 (민감도)
print(recall_score(y_val, pred1))

# F1
print(f1_score(y_val, pred1))

# roc-auc
print(roc_auc_score(y_val, pred2[:,1]))

0.9710055521283159
0.923728813559322
0.8825910931174089
0.9026915113871635
0.9942600875719699

## 예측 및 csv 제출

In [ ]:
pred = lgbmc.predict_proba(test_oh)
pred

array([[9.99902949e-01, 9.70505320e-05],
       [9.94039538e-01, 5.96046235e-03],
       [9.89064296e-01, 1.09357042e-02],
       ...,
       [9.21055611e-01, 7.89443886e-02],
       [9.97900064e-01, 2.09993580e-03],
       [9.97825648e-01, 2.17435192e-03]])

In [ ]:
submit = pd.DataFrame({
    'CLIENTNUM':target_id,
    'Attrition_Flag' :pred[:,1]})
submit.to_csv("result.csv", index = False)

In [ ]:
pd.read_csv("result.csv")

      CLIENTNUM  Attrition_Flag
0     788544108        0.000097
1     719356008        0.005960
2     712142733        0.010936
3     789394833        0.000275
4     742778358        0.000254
...         ...             ...
2021  787361583        0.020905
2022  713474733        0.988881
2023  708486033        0.078944
2024  717683583        0.002100
2025  712887633        0.002174

[2026 rows x 2 columns]

##정리

In [ ]:
# 아래 코드는 실제 시험에서는 확인할 수 없는 부분입니다.
y_test = pd.read_csv()
print(roc_auc_score(y_test, pred[:,1]))

0.9929288094885874